num_networks: 30 # number of networks
num_nodes: 12 # number of nodes
num_pd: 50 # maximum number of P/D points in a node
num_trans_site: 48 # number of sites
max_node_vehicle: 1 # maximum number of vehicles in a node
max_trans_capacity: 3 # maximum capacity of a site
max_trans_pt: 20 # maximum process time in a site
max_from_to: 10 # maximum transportation time in a node

num_jobs: 8 # number of jobs
max_start_after: 0 # maximum request generated time
flexible: True # flexible MHSP
node_init_pos: 0